export type ModuleStatus =
  | "Activo"
  | "Pendiente"
  | "Completado"
  | "Bloqueado"
  | "Destacado"
  | "Vacío"
  | "Error";

export type ModuleRisk = "Bajo" | "Medio" | "Alto" | "Crítico";

export type CommandModule = {
  title: string;
  subtitle: string;
  description: string;
  href: string;
  tag: string;
  group: string;
  status: ModuleStatus;
  risk: ModuleRisk;
  progress: number;
  accent: string;
  items: string[];
  highlights: string[];
};

export const commandModules: CommandModule[] = [
  {
    title: "Reportes Programados",
    subtitle: "Automatización ejecutiva QA",
    description: "Reportes automáticos con frecuencia, destinatarios, evidencia, audit trail, errores, CAPA y decisión QA.",
    href: "/reportes-programados",
    tag: "Reports Auto",
    group: "Automatización",
    status: "Destacado",
    risk: "Alto",
    progress: 92,
    accent: "from-blue-600 to-cyan-400",
    items: ["Frecuencia", "Formato", "Destinatarios", "Audit trail", "QA"],
    highlights: ["PDF / JSON / CSV", "Revisión QA", "Próxima generación"],
  },
  {
    title: "Gestión de Riesgos GxP",
    subtitle: "QRM, RPN y mitigación",
    description: "Matriz de riesgos con severidad, probabilidad, detectabilidad, RPN, CAPA, eficacia y decisión QA.",
    href: "/riesgos",
    tag: "Risk",
    group: "QA",
    status: "Activo",
    risk: "Alto",
    progress: 88,
    accent: "from-red-600 to-rose-500",
    items: ["RPN", "Mitigación", "CAPA", "Eficacia", "QA"],
    highlights: ["Riesgo alto", "Matriz QRM", "Eficacia"],
  },
  {
    title: "Control de Cambios",
    subtitle: "Change control GMP/GACP",
    description: "Gestión formal de cambios sobre procesos, documentos, software, validaciones, entrenamiento y regulación.",
    href: "/cambios",
    tag: "Change",
    group: "QA",
    status: "Activo",
    risk: "Alto",
    progress: 86,
    accent: "from-cyan-500 to-emerald-500",
    items: ["Impacto GxP", "Validación", "Entrenamiento", "Regulatorio", "QA"],
    highlights: ["Evaluación QA", "Eficacia", "Documentos"],
  },
  {
    title: "Workflows QA",
    subtitle: "Aprobaciones y escalamiento",
    description: "Flujos QA con SLA, responsable, aprobador, firma electrónica, escalamiento, evidencia, CAPA y cierre.",
    href: "/workflows",
    tag: "Workflow",
    group: "QA",
    status: "Activo",
    risk: "Alto",
    progress: 84,
    accent: "from-pink-500 to-fuchsia-500",
    items: ["SLA", "Aprobador QA", "Firma", "Escalamiento", "Cierre"],
    highlights: ["Pendientes QA", "SLA", "Firma electrónica"],
  },
  {
    title: "API Regulatoria Avanzada",
    subtitle: "Autoridades y datos regulatorios",
    description: "Conexiones con autoridades, APIs regulatorias, radicaciones externas, cifrado, integridad, audit trail y CAPA.",
    href: "/regulatoria-api",
    tag: "Reg API",
    group: "Regulatorio",
    status: "Activo",
    risk: "Alto",
    progress: 80,
    accent: "from-purple-600 to-violet-500",
    items: ["Autoridad", "Endpoint", "Credencial", "Cifrado", "QA"],
    highlights: ["Integridad", "Audit trail", "Credenciales"],
  },
  {
    title: "Regulatorio",
    subtitle: "Radicaciones y autoridades",
    description: "Radicaciones regulatorias, expedientes, licencias, requerimientos, evidencia documental, vencimientos y CAPA.",
    href: "/regulatorio",
    tag: "Reg",
    group: "Regulatorio",
    status: "Activo",
    risk: "Crítico",
    progress: 90,
    accent: "from-violet-600 to-purple-400",
    items: ["Radicación", "Autoridad", "Expediente", "Licencia", "QA"],
    highlights: ["Trámites", "Vencimientos", "Evidencia"],
  },
  {
    title: "Firmas Electrónicas",
    subtitle: "eSign y registros electrónicos",
    description: "Firmas electrónicas con identidad, MFA, hash, política de firma, evidencia, desviaciones y aprobación QA.",
    href: "/firmas",
    tag: "eSign",
    group: "Part 11",
    status: "Activo",
    risk: "Crítico",
    progress: 94,
    accent: "from-indigo-600 to-blue-500",
    items: ["Firmante", "MFA", "Hash", "Significado", "QA"],
    highlights: ["Part 11", "Hash", "Identidad"],
  },
  {
    title: "Validación 21 CFR Part 11",
    subtitle: "CSV, IQ/OQ/PQ y release",
    description: "Validación del sistema con URS, matriz de riesgo, protocolos, pruebas, audit trail, firmas e integridad de datos.",
    href: "/part11",
    tag: "Part 11",
    group: "Validación",
    status: "Activo",
    risk: "Crítico",
    progress: 89,
    accent: "from-violet-700 to-indigo-500",
    items: ["URS", "IQ/OQ/PQ", "Audit trail", "Release", "QA"],
    highlights: ["Validación", "Release", "Integridad"],
  },
  {
    title: "Backups y Restauración",
    subtitle: "Continuidad e integridad",
    description: "Backups, restauración, snapshots, retención, cifrado, hash, pruebas de restore, evidencia y decisión QA.",
    href: "/backups",
    tag: "Backup",
    group: "DataOps",
    status: "Activo",
    risk: "Crítico",
    progress: 87,
    accent: "from-rose-600 to-orange-500",
    items: ["Backup", "Restore", "Hash", "Cifrado", "Retención"],
    highlights: ["Restore probado", "Hash", "Cifrado"],
  },
  {
    title: "Conectores e Integraciones",
    subtitle: "API, webhooks, LIMS y ERP",
    description: "Integraciones externas con autenticación, cifrado, mapeo, validaciones, audit trail, evidencia y CAPA.",
    href: "/integraciones",
    tag: "API",
    group: "Sistema",
    status: "Activo",
    risk: "Alto",
    progress: 82,
    accent: "from-orange-500 to-amber-400",
    items: ["API", "Webhook", "LIMS", "ERP", "QA"],
    highlights: ["Mapeo", "Validación", "Cifrado"],
  },
  {
    title: "Calidad QA",
    subtitle: "Muestreo y control analítico",
    description: "Muestras, análisis, laboratorio, resultados, veredicto QA, evidencia y trazabilidad completa.",
    href: "/calidad",
    tag: "QA",
    group: "QA",
    status: "Activo",
    risk: "Alto",
    progress: 91,
    accent: "from-emerald-600 to-teal-400",
    items: ["Muestra", "COA", "Resultado", "Liberación", "QA"],
    highlights: ["Muestreo", "Veredicto", "COA"],
  },
  {
    title: "Desviaciones / CAPA",
    subtitle: "No conformidades y causa raíz",
    description: "Investigación de desviaciones, impacto, causa raíz, acciones inmediatas, CAPA, eficacia y cierre QA.",
    href: "/desviaciones",
    tag: "CAPA",
    group: "QA",
    status: "Activo",
    risk: "Crítico",
    progress: 85,
    accent: "from-rose-600 to-red-500",
    items: ["Desviación", "Causa raíz", "CAPA", "Eficacia", "Cierre"],
    highlights: ["Causa raíz", "CAPA", "Eficacia"],
  },
  {
    title: "Documentos Controlados",
    subtitle: "SOP, versiones y vigencia",
    description: "Control documental de SOP, formatos, versiones, vigencia, obsolescencia, entrenamiento y evidencia.",
    href: "/documentos",
    tag: "GMP",
    group: "Documental",
    status: "Activo",
    risk: "Alto",
    progress: 84,
    accent: "from-slate-800 to-slate-500",
    items: ["SOP", "Versión", "Vigencia", "Entrenamiento", "QA"],
    highlights: ["SOP", "Versiones", "Obsolescencia"],
  },
  {
    title: "Entrenamiento y Competencia",
    subtitle: "Personal, SOP y liberación",
    description: "Entrenamiento por colaborador, SOP, versión documental, instructor, evaluación, competencia y reentrenamiento.",
    href: "/entrenamiento",
    tag: "GMP",
    group: "GMP",
    status: "Activo",
    risk: "Alto",
    progress: 83,
    accent: "from-teal-600 to-green-400",
    items: ["Colaborador", "SOP", "Evaluación", "Competencia", "QA"],
    highlights: ["Competencia", "Reentrenamiento", "SOP"],
  },
  {
    title: "Equipos GMP",
    subtitle: "Calibración y mantenimiento",
    description: "Equipos críticos, códigos de activo, calibración, mantenimiento, certificados, CAPA y liberación QA.",
    href: "/equipos",
    tag: "GMP",
    group: "GMP",
    status: "Activo",
    risk: "Alto",
    progress: 78,
    accent: "from-cyan-600 to-blue-400",
    items: ["Equipo", "Calibración", "Mantenimiento", "Certificado", "QA"],
    highlights: ["Calibración", "Activo", "Mantenimiento"],
  },
  {
    title: "Proveedores",
    subtitle: "Calificación GMP/GACP",
    description: "Evaluación, calificación, criticidad, riesgo, documentación, auditoría, evidencia y reevaluación de proveedores.",
    href: "/proveedores",
    tag: "Supplier",
    group: "Proveedor",
    status: "Activo",
    risk: "Alto",
    progress: 77,
    accent: "from-purple-500 to-pink-400",
    items: ["Proveedor", "Criticidad", "Auditoría", "Documentos", "QA"],
    highlights: ["Calificación", "Criticidad", "Auditoría"],
  },
  {
    title: "Inventario",
    subtitle: "Stock, cuarentena y liberación",
    description: "Movimientos de inventario, ubicación, cantidad, cuarentena, liberación QA y condiciones de almacenamiento.",
    href: "/inventario",
    tag: "GMP",
    group: "Operación",
    status: "Activo",
    risk: "Alto",
    progress: 86,
    accent: "from-blue-600 to-sky-400",
    items: ["Stock", "Ubicación", "Cuarentena", "Liberación", "QA"],
    highlights: ["Stock", "Cuarentena", "Movimientos"],
  },
  {
    title: "Recepción",
    subtitle: "Ingreso y liberación inicial",
    description: "Control de ingreso de material vegetal, lotes, insumos, empaque, estado sanitario y decisión QA.",
    href: "/recepcion",
    tag: "GACP/GMP",
    group: "Operación",
    status: "Activo",
    risk: "Alto",
    progress: 81,
    accent: "from-emerald-600 to-lime-400",
    items: ["Ingreso", "Lote", "Proveedor", "Cuarentena", "QA"],
    highlights: ["Ingreso", "Lote", "Liberación"],
  },
  {
    title: "Cultivos",
    subtitle: "Producción agrícola GACP",
    description: "Registro validado de cultivos, predio, genética, área, responsable, evidencia y trazabilidad.",
    href: "/cultivos",
    tag: "GACP",
    group: "GACP",
    status: "Activo",
    risk: "Medio",
    progress: 74,
    accent: "from-green-600 to-emerald-400",
    items: ["Predio", "Genética", "Área", "Responsable", "Evidencia"],
    highlights: ["GACP", "Trazabilidad", "Predio"],
  },
  {
    title: "Propagación",
    subtitle: "Clones, madres y trazabilidad",
    description: "Control de propagación, genética, etapa, ambiente, evidencia, responsable y soporte técnico.",
    href: "/propagacion",
    tag: "GACP",
    group: "GACP",
    status: "Activo",
    risk: "Medio",
    progress: 76,
    accent: "from-lime-600 to-emerald-400",
    items: ["Madres", "Clones", "Genética", "Etapa", "Evidencia"],
    highlights: ["Clones", "Madres", "Genética"],
  },
  {
    title: "Cosecha",
    subtitle: "Corte, lote y rendimiento",
    description: "Trazabilidad de cosecha, lote, biomasa, responsables, rendimientos y control documental.",
    href: "/cosecha",
    tag: "GACP",
    group: "GACP",
    status: "Activo",
    risk: "Medio",
    progress: 73,
    accent: "from-yellow-600 to-lime-400",
    items: ["Corte", "Lote", "Biomasa", "Rendimiento", "QA"],
    highlights: ["Corte", "Rendimiento", "Lote"],
  },
  {
    title: "Genéticas",
    subtitle: "Banco genético y variedades",
    description: "Control de variedades, madres, códigos, características, estado y trazabilidad genética.",
    href: "/geneticas",
    tag: "GACP",
    group: "GACP",
    status: "Activo",
    risk: "Medio",
    progress: 72,
    accent: "from-green-700 to-teal-400",
    items: ["Variedad", "Madre", "Código", "Estado", "Trazabilidad"],
    highlights: ["Variedades", "Madres", "Códigos"],
  },
  {
    title: "Empresas y Licencias",
    subtitle: "Multiempresa, sedes y alcance",
    description: "Razón social, sedes, licencias, responsables, alcance autorizado, estado GACP/GMP, evidencia y CAPA.",
    href: "/empresas",
    tag: "Company",
    group: "Empresa",
    status: "Activo",
    risk: "Alto",
    progress: 79,
    accent: "from-emerald-700 to-cyan-500",
    items: ["Empresa", "Licencia", "Sede", "Alcance", "QA"],
    highlights: ["Licencias", "Multiempresa", "Sedes"],
  },
  {
    title: "GIS / Mapa Operacional",
    subtitle: "Predios y zonas críticas",
    description: "Control georreferenciado de empresas, predios, áreas, zonas críticas, coordenadas, evidencia y decisión QA.",
    href: "/gis",
    tag: "GIS",
    group: "GIS",
    status: "Activo",
    risk: "Medio",
    progress: 70,
    accent: "from-cyan-700 to-lime-400",
    items: ["Coordenadas", "Predio", "Zona", "Riesgo", "QA"],
    highlights: ["Mapa", "Coordenadas", "Zonas"],
  },
  {
    title: "Reportes y KPIs",
    subtitle: "Cumplimiento ejecutivo",
    description: "Reportes ejecutivos, KPIs, periodos, módulos incluidos, hallazgos, riesgos, acciones requeridas y QA.",
    href: "/reportes",
    tag: "Reports",
    group: "Reportes",
    status: "Activo",
    risk: "Medio",
    progress: 84,
    accent: "from-blue-700 to-indigo-400",
    items: ["KPI", "Periodo", "Hallazgos", "Riesgos", "QA"],
    highlights: ["KPIs", "Ejecutivo", "Riesgos"],
  },
  {
    title: "Notificaciones y Alertas",
    subtitle: "Vencimientos y escalamiento",
    description: "Alertas, vencimientos, CAPA pendientes, auditorías, calibraciones, documentos, licencias y responsables.",
    href: "/notificaciones",
    tag: "Alertas",
    group: "Alertas",
    status: "Activo",
    risk: "Alto",
    progress: 83,
    accent: "from-amber-600 to-orange-400",
    items: ["Alerta", "Vencimiento", "CAPA", "Escalamiento", "QA"],
    highlights: ["Vencimientos", "CAPA", "Escalamiento"],
  },
  {
    title: "CSV / DataOps",
    subtitle: "Importación y validación",
    description: "Importaciones, exportaciones, migraciones, conciliaciones, hash, backup, evidencia, CAPA y decisión QA.",
    href: "/csv",
    tag: "CSV",
    group: "DataOps",
    status: "Activo",
    risk: "Alto",
    progress: 81,
    accent: "from-sky-600 to-cyan-400",
    items: ["Importación", "Exportación", "Hash", "Backup", "QA"],
    highlights: ["DataOps", "Hash", "Migración"],
  },
  {
    title: "Usuarios y Accesos",
    subtitle: "Roles, MFA y seguridad",
    description: "Usuarios, roles, permisos, MFA, firma electrónica, revisión periódica, segregación de funciones y CAPA.",
    href: "/usuarios",
    tag: "Security",
    group: "Seguridad",
    status: "Activo",
    risk: "Crítico",
    progress: 88,
    accent: "from-slate-900 to-blue-600",
    items: ["Usuario", "Rol", "MFA", "Firma", "QA"],
    highlights: ["MFA", "Roles", "Segregación"],
  },
  {
    title: "Recall / Retiro",
    subtitle: "Retiro de producto GMP",
    description: "Alertas, bloqueo de lote, retiro preventivo u obligatorio, autoridad, recuperación, CAPA y cierre QA.",
    href: "/recall",
    tag: "Recall",
    group: "GMP",
    status: "Activo",
    risk: "Crítico",
    progress: 82,
    accent: "from-red-700 to-orange-500",
    items: ["Lote", "Bloqueo", "Autoridad", "Recuperación", "QA"],
    highlights: ["Bloqueo", "Autoridad", "Cierre"],
  },
  {
    title: "Retención y Estabilidad",
    subtitle: "Muestras y estabilidad",
    description: "Muestras de retención, contramuestras, estabilidad, custodia, almacenamiento, vencimiento y decisión QA.",
    href: "/retencion",
    tag: "GMP",
    group: "GMP",
    status: "Activo",
    risk: "Alto",
    progress: 80,
    accent: "from-indigo-700 to-sky-500",
    items: ["Muestra", "Custodia", "Estabilidad", "Vencimiento", "QA"],
    highlights: ["Retención", "Custodia", "Estabilidad"],
  },
  {
    title: "Residuos y Disposición",
    subtitle: "Gestión ambiental GMP/GACP",
    description: "Residuos por área, lote, riesgo, cantidad, tratamiento, gestor autorizado, disposición final y QA.",
    href: "/residuos",
    tag: "Waste",
    group: "Ambiental",
    status: "Activo",
    risk: "Alto",
    progress: 71,
    accent: "from-lime-700 to-green-400",
    items: ["Residuo", "Gestor", "Tratamiento", "Certificado", "QA"],
    highlights: ["Gestor", "Disposición", "Certificado"],
  },
  {
    title: "Limpieza y Saneamiento",
    subtitle: "Higiene, SOP y liberación",
    description: "Limpieza, desinfección, SOP, productos, concentraciones, inspección preoperacional, hisopado y QA.",
    href: "/saneamiento",
    tag: "GMP",
    group: "GMP",
    status: "Activo",
    risk: "Alto",
    progress: 78,
    accent: "from-teal-700 to-cyan-400",
    items: ["Limpieza", "SOP", "Producto", "Hisopado", "QA"],
    highlights: ["Saneamiento", "Hisopado", "Liberación"],
  },
  {
    title: "Manejo Integrado de Plagas",
    subtitle: "MIP, trampas y control",
    description: "Inspecciones, trampas, hallazgos, actividad de plagas, productos aplicados, proveedor, evidencia y CAPA.",
    href: "/plagas",
    tag: "MIP",
    group: "GACP",
    status: "Activo",
    risk: "Alto",
    progress: 69,
    accent: "from-amber-700 to-lime-500",
    items: ["Trampas", "Hallazgos", "Actividad", "Proveedor", "CAPA"],
    highlights: ["MIP", "Trampas", "Hallazgos"],
  },
  {
    title: "Predios",
    subtitle: "Infraestructura agrícola base",
    description: "Predios, áreas, ubicación, capacidad productiva y condiciones de cumplimiento.",
    href: "/predios",
    tag: "Base",
    group: "Base",
    status: "Activo",
    risk: "Bajo",
    progress: 70,
    accent: "from-slate-600 to-emerald-400",
    items: ["Predio", "Área", "Ubicación", "Capacidad", "Cumplimiento"],
    highlights: ["Predio", "Área", "Base"],
  },
  {
    title: "Extracción BHO",
    subtitle: "Closed-loop, solvente y QA",
    description: "Trazabilidad de extracción BHO con lote de origen, solvente documentado, sistema cerrado, purge, limpieza, seguridad, evidencia, desviaciones, CAPA y decisión QA.",
    href: "/bho",
    tag: "BHO",
    group: "Extracción",
    status: "Activo",
    risk: "Crítico",
    progress: 82,
    accent: "from-orange-600 to-amber-400",
    items: ["Closed-loop", "Solvente", "Purge", "Cuarentena", "QA"],
    highlights: ["Solvente documentado", "Sistema cerrado", "Purge QA"],
  },
  {
    title: "Live Rosin",
    subtitle: "Solventless premium y QA",
    description: "Trazabilidad Live Rosin con fresh frozen, bubble hash, micronaje, press, curado, limpieza, evidencia, cuarentena, desviaciones, CAPA y decisión QA.",
    href: "/live-rosin",
    tag: "Rosin",
    group: "Extracción",
    status: "Activo",
    risk: "Alto",
    progress: 84,
    accent: "from-lime-600 to-emerald-400",
    items: ["Fresh frozen", "Bubble hash", "Press", "Curado", "QA"],
    highlights: ["Solventless", "Micronaje", "Premium"],
  },
  {
    title: "Bubble Hash",
    subtitle: "Ice water hash y micronaje",
    description: "Trazabilidad Bubble Hash con material congelado, agua/hielo o consumibles críticos, bolsas micron, secado, limpieza, evidencia, cuarentena y liberación QA.",
    href: "/bubble-hash",
    tag: "Hash",
    group: "Extracción",
    status: "Activo",
    risk: "Alto",
    progress: 80,
    accent: "from-cyan-600 to-sky-400",
    items: ["WPFF", "Micronaje", "Secado", "Solventless", "QA"],
    highlights: ["Ice water", "Micron select", "Hash para rosin"],
  },
  {
    title: "Post-Extracción GMP",
    subtitle: "Purificación, fraccionamiento y QA",
    description: "Trazabilidad post-extracción para winterización, filtración, decarboxilación, destilación, fraccionamiento, remediación aprobada por QA, formulación intermedia, evidencia, desviaciones y CAPA.",
    href: "/post-extraccion",
    tag: "Post",
    group: "Extracción",
    status: "Activo",
    risk: "Alto",
    progress: 83,
    accent: "from-fuchsia-600 to-indigo-500",
    items: ["Winterización", "Filtración", "Destilación", "Cuarentena", "QA"],
    highlights: ["Batch record", "Liberación QA", "Post-extracción"],
  },

  {
    title: "ICA",
    subtitle: "Control fitosanitario y agrícola",
    description: "Seguimiento de trámites, radicaciones, conceptos, predios, soportes, requerimientos y evidencias ante ICA bajo control QA.",
    href: "/ica",
    tag: "ICA",
    group: "Regulatorio",
    status: "Activo",
    risk: "Alto",
    progress: 78,
    accent: "from-emerald-700 to-lime-500",
    items: ["Predios", "Conceptos", "Radicados", "Soportes", "QA"],
    highlights: ["ICA", "Fitosanitario", "Predios"],
  },

  {
    title: "INVIMA",
    subtitle: "Soportes sanitarios y GMP",
    description: "Seguimiento de trámites, soportes sanitarios, certificaciones, expedientes, requerimientos y evidencias ante INVIMA bajo control QA.",
    href: "/invima",
    tag: "INVIMA",
    group: "Regulatorio",
    status: "Activo",
    risk: "Crítico",
    progress: 82,
    accent: "from-purple-700 to-fuchsia-500",
    items: ["Expediente", "GMP", "Radicado", "Requerimiento", "QA"],
    highlights: ["INVIMA", "GMP", "Sanitario"],
  },

  {
    title: "PEAS",
    subtitle: "Planes, permisos y anexos",
    description: "Control PEAS de planes, permisos, anexos, soportes, requerimientos, seguimiento documental, evidencia, desviaciones, CAPA y decisión QA.",
    href: "/peas",
    tag: "PEAS",
    group: "Regulatorio",
    status: "Activo",
    risk: "Alto",
    progress: 76,
    accent: "from-cyan-700 to-blue-500",
    items: ["Plan", "Permiso", "Anexo", "Seguimiento", "QA"],
    highlights: ["PEAS", "Permisos", "Anexos"],
  },

  {
    title: "Ministerio de Justicia",
    subtitle: "Licencias, cupos y seguimiento",
    description: "Seguimiento regulatorio de licencias de cannabis, modificaciones, renovaciones, cupos, informes periódicos, requerimientos, radicados, resoluciones, evidencia, desviaciones, CAPA y decisión QA.",
    href: "/minjusticia",
    tag: "MinJus",
    group: "Regulatorio",
    status: "Activo",
    risk: "Crítico",
    progress: 84,
    accent: "from-green-800 to-emerald-500",
    items: ["Licencias", "Cupos", "Informes", "Radicados", "QA"],
    highlights: ["Ministerio de Justicia", "Cupos", "Licencias"],
  },

  {
    title: "Estado de la App",
    subtitle: "Salud del sistema y diagnóstico",
    description: "Módulo centralizado para revisar salud del sistema, almacenamiento local, módulos activos, entorno de ejecución, conectividad, diagnósticos y exportación de estado sin interferir con la pantalla.",
    href: "/estado-app",
    tag: "Status",
    group: "Sistema",
    status: "Activo",
    risk: "Medio",
    progress: 93,
    accent: "from-slate-900 to-emerald-500",
    items: ["Servidor", "LocalStorage", "Módulos", "Diagnóstico", "Export"],
    highlights: ["Sin overlay", "Dev indicator oculto", "Diagnóstico"],
  },

  {
    title: "FNE / Fondo Nacional de Estupefacientes",
    subtitle: "Sustancias, cupos y reportes",
    description: "Seguimiento interno de trámites, reportes, soportes, requerimientos, cupos, controles de sustancias fiscalizadas, evidencias, desviaciones, CAPA y decisión QA relacionados con FNE.",
    href: "/fne",
    tag: "FNE",
    group: "Regulatorio",
    status: "Activo",
    risk: "Crítico",
    progress: 82,
    accent: "from-rose-800 to-orange-500",
    items: ["Reportes", "Cupos", "Movimientos", "Soportes", "QA"],
    highlights: ["FNE", "Sustancias fiscalizadas", "Conciliación"],
  },

  {
    title: "DIAN / Comercio Exterior",
    subtitle: "Aduanas, importaciones y exportaciones",
    description: "Seguimiento regulatorio de importaciones, exportaciones, soportes aduaneros, documentos tributarios, certificados, declaraciones, radicados, requerimientos DIAN, conciliación documental, evidencia, desviaciones, CAPA y decisión QA.",
    href: "/dian",
    tag: "DIAN",
    group: "Regulatorio",
    status: "Activo",
    risk: "Alto",
    progress: 79,
    accent: "from-yellow-700 to-orange-500",
    items: ["Importación", "Exportación", "Aduanas", "Soportes", "QA"],
    highlights: ["DIAN", "Comercio exterior", "Conciliación"],
  },
];









